apiVersion: apps/v1

kind: Deployment

metadata:

  name: node-app-deployment

  labels:

    app: node-app

spec:

  replicas: 1

  selector:

    matchLabels:

      app: node-app

  template:

    metadata:

      labels:

        app: node-app

    spec:

      containers:

      - name: node-app

        image: pavanktm/node-app:1.0.0

        ports:

        - containerPort: 9981

---
kind: Service 
apiVersion: v1 
metadata:
  name: node-app-service 
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - nodePort: 30163
      port: 9981 
      targetPort: 9981
